GET http://localhost:3000/details
###

GET http://localhost:3000/details/67a7365d18b170b368b1ea6c

###

POST http://localhost:3000/details
Content-Type: application/json

{
    "name":"Blyat"

}
###
DELETE http://localhost:3000/details/67ae2a2b9344b87b731f2b22